ParseException: don't require file position info
A parse exception uses the file position to indicate the place where the
exception occurred. However, for issues like an encoding that couldn't
be auto-guessed, no position is available. Hence, this is now correctly
handled.